//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("opencodechemsModel", "FK_dbo_Profile_dbo_User_username", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OpenCodeChems.Server.DataAccess.User), "Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OpenCodeChems.Server.DataAccess.Profile), true)]

#endregion

namespace OpenCodeChems.Server.DataAccess
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class opencodechemsContext : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto opencodechemsContext usando la cadena de conexión encontrada en la sección 'opencodechemsContext' del archivo de configuración de la aplicación.
        /// </summary>
        public opencodechemsContext() : base("name=opencodechemsContext", "opencodechemsContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto opencodechemsContext.
        /// </summary>
        public opencodechemsContext(string connectionString) : base(connectionString, "opencodechemsContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto opencodechemsContext.
        /// </summary>
        public opencodechemsContext(EntityConnection connection) : base(connection, "opencodechemsContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Profiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Users. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opencodechemsModel", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Profile.
        /// </summary>
        /// <param name="nickname">Valor inicial de la propiedad nickname.</param>
        /// <param name="username">Valor inicial de la propiedad username.</param>
        public static Profile CreateProfile(global::System.String nickname, global::System.String username)
        {
            Profile profile = new Profile();
            profile.nickname = nickname;
            profile.username = username;
            return profile;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nickname
        {
            get
            {
                return _nickname;
            }
            set
            {
                if (_nickname != value)
                {
                    OnnicknameChanging(value);
                    ReportPropertyChanging("nickname");
                    _nickname = StructuralObject.SetValidValue(value, false, "nickname");
                    ReportPropertyChanged("nickname");
                    OnnicknameChanged();
                }
            }
        }
        private global::System.String _nickname;
        partial void OnnicknameChanging(global::System.String value);
        partial void OnnicknameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> victories
        {
            get
            {
                return _victories;
            }
            set
            {
                OnvictoriesChanging(value);
                ReportPropertyChanging("victories");
                _victories = StructuralObject.SetValidValue(value, "victories");
                ReportPropertyChanged("victories");
                OnvictoriesChanged();
            }
        }
        private Nullable<global::System.Int32> _victories;
        partial void OnvictoriesChanging(Nullable<global::System.Int32> value);
        partial void OnvictoriesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] imageProfile
        {
            get
            {
                return StructuralObject.GetValidValue(_imageProfile);
            }
            set
            {
                OnimageProfileChanging(value);
                ReportPropertyChanging("imageProfile");
                _imageProfile = StructuralObject.SetValidValue(value, true, "imageProfile");
                ReportPropertyChanged("imageProfile");
                OnimageProfileChanged();
            }
        }
        private global::System.Byte[] _imageProfile;
        partial void OnimageProfileChanging(global::System.Byte[] value);
        partial void OnimageProfileChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> @default
        {
            get
            {
                return _default;
            }
            set
            {
                OndefaultChanging(value);
                ReportPropertyChanging("default");
                _default = StructuralObject.SetValidValue(value, "default");
                ReportPropertyChanged("default");
                OndefaultChanged();
            }
        }
        private Nullable<global::System.Int32> _default;
        partial void OndefaultChanging(Nullable<global::System.Int32> value);
        partial void OndefaultChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opencodechemsModel", "FK_dbo_Profile_dbo_User_username", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "User").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opencodechemsModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto User.
        /// </summary>
        /// <param name="username">Valor inicial de la propiedad username.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static User CreateUser(global::System.String username, global::System.String password, global::System.String email, global::System.String name)
        {
            User user = new User();
            user.username = username;
            user.password = password;
            user.email = email;
            user.name = name;
            return user;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false, "username");
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opencodechemsModel", "FK_dbo_Profile_dbo_User_username", "Profile")]
        public EntityCollection<Profile> Profiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Profile>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Profile>("opencodechemsModel.FK_dbo_Profile_dbo_User_username", "Profile", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
