//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string nickname { get; set; }
        public Nullable<int> victories { get; set; }
        public byte[] imageProfile { get; set; }
        public byte[] avatar { get; set; }
        public Nullable<int> defaults { get; set; }
        public string username { get; set; }
    
        public virtual User User { get; set; }
    }
}
